# Generated by Django 6.0.7 on 2026-08-15 13:05

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0019_systemannouncement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedDaycare',
            fields=[
            ],
            options={
                'verbose_name': 'Daycare Management',
                'verbose_name_plural': '1. Daycare Management',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.daycare',),
        ),
        migrations.CreateModel(
            name='ManagedDaycareSubscription',
            fields=[
            ],
            options={
                'verbose_name': 'Assigned Subscription',
                'verbose_name_plural': '4. Assigned Subscriptions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.daycaresubscription',),
        ),
        migrations.CreateModel(
            name='ManagedSubscriptionPlan',
            fields=[
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': '3. Subscription Plans',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.subscriptionplan',),
        ),
        migrations.CreateModel(
            name='ManagedUser',
            fields=[
            ],
            options={
                'verbose_name': 'Platform User',
                'verbose_name_plural': '2. Platform Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
