# Generated by Django 6.0.7 on 2026-08-02 06:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_feetype_invoice_invoiceitem_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Food', 'Food'), ('Medication', 'Medication'), ('Environmental', 'Environmental'), ('Other', 'Other')], max_length=50)),
                ('allergen', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe'), ('Anaphylactic', 'Anaphylactic')], max_length=50)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('emergency_response', models.TextField(blank=True, null=True)),
                ('epipen_required', models.BooleanField(default=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergy_records', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True)),
                ('ohip_number', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_physician', models.CharField(blank=True, max_length=255, null=True)),
                ('clinic', models.CharField(blank=True, max_length=255, null=True)),
                ('dentist', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital_preference', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_medical_consent', models.BooleanField(default=False)),
                ('special_needs', models.TextField(blank=True, null=True)),
                ('health_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_profiles', to='core.daycare')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('route', models.CharField(blank=True, max_length=100, null=True)),
                ('frequency', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('prescribing_doctor', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_consent', models.BooleanField(default=False)),
                ('storage_location', models.CharField(blank=True, max_length=255, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_records', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('dosage_given', models.CharField(blank=True, max_length=100, null=True)),
                ('outcome', models.CharField(blank=True, max_length=255, null=True)),
                ('missed_dose', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('teacher_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_medications', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='core.medication')),
                ('witness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='witnessed_medications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
