# Generated by Django 6.0.7 on 2026-08-02 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_documentcategory_document_documentexpiration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('severity', models.CharField(default='Low', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_date', models.DateField()),
                ('time', models.TimeField()),
                ('incident_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('action_taken', models.TextField()),
                ('witness', models.CharField(blank=True, max_length=255, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('severity', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='core.daycare')),
                ('reporting_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to='core.employee')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(default='Medium', max_length=50)),
                ('completion_status', models.CharField(default='Open', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='core.daycare')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_corrective_actions', to=settings.AUTH_USER_MODEL)),
                ('inspection_finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.inspectionfinding')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspection_date', models.DateField()),
                ('inspector_name', models.CharField(max_length=255)),
                ('inspection_type', models.CharField(max_length=100)),
                ('pass_fail', models.CharField(blank=True, max_length=50, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='core.daycare')),
            ],
        ),
        migrations.AddField(
            model_name='inspectionfinding',
            name='inspection_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.inspectionvisit'),
        ),
    ]
