# Generated by Django 6.0.7 on 2026-08-14 15:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auditlog_subscriptioninvoice_subscriptionpayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='billing_cycle',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='classroom_management',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='compliance',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='csv_export',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='notifications',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='pdf_export',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='price',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='reports',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='staff_management',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='storage_limit',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='student_management',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='annual_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='quarterly_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='plans', to='core.subscriptionfeature'),
        ),
    ]
