# Generated by Django 6.0.7 on 2026-08-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_subscriptionfeature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_classrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_storage_mb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_students',
            field=models.IntegerField(default=0),
        ),
    ]
