# Generated by Django 6.0.7 on 2026-08-17 08:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_systemannouncement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaycareLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=100)),
                ('license_type', models.CharField(blank=True, max_length=100, null=True)),
                ('issuing_authority', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('document_path', models.CharField(blank=True, max_length=2048, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daycare', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='core.daycare')),
            ],
        ),
    ]
