# Generated by Django 6.0.7 on 2026-08-17 09:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_daycarelicense'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaycareEmergencyInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=100)),
                ('alternate_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('police_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('fire_service_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daycare', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_info', to='core.daycare')),
            ],
        ),
        migrations.CreateModel(
            name='DaycareHoliday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('holiday_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='core.daycare')),
            ],
        ),
    ]
