# Generated by Django 6.0.7 on 2026-08-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_daycareemergencyinformation_daycareholiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycarelicense',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
