# Generated by Django 6.0.7 on 2026-08-17 11:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_branch_address_branch_capacity_branch_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaycareSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('time_format', models.CharField(default='24h', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('week_start_day', models.CharField(default='Monday', max_length=15)),
                ('default_operating_start', models.TimeField(blank=True, null=True)),
                ('default_operating_end', models.TimeField(blank=True, null=True)),
                ('allow_parent_notifications', models.BooleanField(default=True)),
                ('allow_staff_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daycare', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.daycare')),
            ],
        ),
    ]
