# Generated by Django 6.0.7 on 2026-08-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_daycaresettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dietary_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='special_needs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
