# Generated by Django 6.0.7 on 2026-08-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_student_dietary_restrictions_student_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='administrative_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='child_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
