# Generated by Django 6.0.7 on 2026-08-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_childvaccinationrecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroomstudent',
            unique_together=set(),
        ),
    ]
