# Generated by Django 6.0.7 on 2026-08-25 13:38

from django.db import migrations

def backfill_enrollments(apps, schema_editor):
    Student = apps.get_model('core', 'Student')
    ChildEnrollment = apps.get_model('core', 'ChildEnrollment')
    
    for student in Student.objects.all():
        ChildEnrollment.objects.create(
            student=student,
            application_date=student.admission_date,
            enrollment_date=student.admission_date,
            start_date=student.joining_date,
            status=student.status
        )

def reverse_backfill(apps, schema_editor):
    ChildEnrollment = apps.get_model('core', 'ChildEnrollment')
    ChildEnrollment.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_student_medical_notes_childenrollment'),
    ]

    operations = [
        migrations.RunPython(backfill_enrollments, reverse_backfill),
    ]
