# Generated by Django 6.0.7 on 2026-08-26 08:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20260825_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('primary_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('primary_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='core.daycare')),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('preferred_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='core.daycare')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuardianCommunicationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_alerts', models.BooleanField(default=True)),
                ('sms_alerts', models.BooleanField(default=False)),
                ('emergency_alerts_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guardian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_preference', to='core.guardian')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyChild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_children', to='core.family')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_families', to='core.student')),
            ],
            options={
                'unique_together': {('family', 'student')},
            },
        ),
        migrations.CreateModel(
            name='FamilyGuardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_guardians', to='core.family')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_families', to='core.guardian')),
            ],
            options={
                'unique_together': {('family', 'guardian')},
            },
        ),
    ]
