# Generated by Django 6.0.7 on 2026-08-26 11:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_guardianinvitation_guardianpasswordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('form_type', models.CharField(choices=[('General', 'General'), ('Medical', 'Medical'), ('Trip', 'Field Trip'), ('Photo', 'Photo/Media'), ('Emergency', 'Emergency'), ('Other', 'Other')], default='General', max_length=50)),
                ('requires_signature', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Archived', 'Archived')], default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_consent_forms', to=settings.AUTH_USER_MODEL)),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_forms', to='core.daycare')),
            ],
        ),
        migrations.CreateModel(
            name='ConsentFormAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Signed', 'Signed'), ('Declined', 'Declined')], default='Pending', max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_consent_forms', to=settings.AUTH_USER_MODEL)),
                ('consent_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.consentform')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_assignments', to='core.family')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_assignments', to='core.student')),
            ],
            options={
                'unique_together': {('consent_form', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ConsentFormSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signature_name', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('agreement_text', models.TextField()),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='core.consentformassignment')),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_signatures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('message_type', models.CharField(choices=[('guardian_to_staff', 'Guardian to Staff'), ('staff_to_guardian', 'Staff to Guardian')], default='guardian_to_staff', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_messages', to='core.daycare')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.family')),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='core.familymessage')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_family_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_family_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
