# Generated by Django 6.0.7 on 2026-08-26 13:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_consentform_consentformassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='familyguardian',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.CreateModel(
            name='FamilyAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.family')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
