# Generated by Django 6.0.7 on 2026-08-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_family_secondary_phone_familyguardian_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentemergencycontact',
            name='approval_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='studentemergencycontact',
            name='pending_changes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentpickup',
            name='approval_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='studentpickup',
            name='id_proof_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='studentpickup',
            name='pending_changes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
