# Generated by Django 6.0.7 on 2026-08-27 17:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_studentemergencycontact_approval_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_number', models.CharField(max_length=100, unique=True)),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('applicant_phone', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('waitlisted', 'Waitlisted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='draft', max_length=50)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_applications', to='core.daycare')),
            ],
        ),
    ]
