# Generated by Django 6.0.7 on 2026-08-29 05:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_registrationapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationapplication',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='registrationapplication',
            name='application_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
