# Generated by Django 6.0.7 on 2026-08-29 06:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_registrationapplication_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentform',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='EnrollmentForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fields_schema', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_forms', to='core.daycare')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='enrollment_documents/')),
                ('status', models.CharField(choices=[('required', 'Required'), ('uploaded', 'Uploaded'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='uploaded', max_length=50)),
                ('verification_status', models.CharField(default='pending', max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='core.registrationapplication')),
            ],
        ),
    ]
