# Generated by Django 6.0.7 on 2026-08-29 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_consentform_version_enrollmentform_uploadeddocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedDocument',
        ),
    ]
