# Generated by Django 6.0.7 on 2026-08-29 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_waitlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='childenrollment',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='core.registrationapplication'),
        ),
    ]
