# Generated by Django 6.0.7 on 2026-08-29 12:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_rename_hire_date_employee_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCertification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certification_name', models.CharField(max_length=255)),
                ('certification_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issuing_organization', models.CharField(max_length=255)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('document_reference', models.CharField(blank=True, max_length=2048, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeQualification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qualification_name', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('qualification_type', models.CharField(max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('document_reference', models.CharField(blank=True, max_length=2048, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daycare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_types', to='core.daycare')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='employees', to='core.employeetype'),
        ),
    ]
