# Generated by Django 6.0.7 on 2026-08-29 14:38

import django.contrib.auth.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_employeecertification_employeequalification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedDaycare',
            fields=[
            ],
            options={
                'verbose_name': 'Daycare Management',
                'verbose_name_plural': '1. Daycare Management',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.daycare',),
        ),
        migrations.CreateModel(
            name='ManagedDaycareSubscription',
            fields=[
            ],
            options={
                'verbose_name': 'Assigned Subscription',
                'verbose_name_plural': '4. Assigned Subscriptions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.daycaresubscription',),
        ),
        migrations.CreateModel(
            name='ManagedSubscriptionPlan',
            fields=[
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': '3. Subscription Plans',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.subscriptionplan',),
        ),
        migrations.CreateModel(
            name='ManagedUser',
            fields=[
            ],
            options={
                'verbose_name': 'Platform User',
                'verbose_name_plural': '2. Platform Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='familyauditlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='familymessage',
            options={},
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='annual_price',
            new_name='price',
        ),
        migrations.AlterUniqueTogether(
            name='consentformassignment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='familychild',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='familyguardian',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='staffattendance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='branch',
            name='address',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='status',
        ),
        migrations.RemoveField(
            model_name='daycare',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='daycaresubscription',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='daycaresubscription',
            name='billing_cycle',
        ),
        migrations.RemoveField(
            model_name='daycaresubscription',
            name='suspended_at',
        ),
        migrations.RemoveField(
            model_name='daycaresubscription',
            name='suspended_by',
        ),
        migrations.RemoveField(
            model_name='daycaresubscription',
            name='suspension_reason',
        ),
        migrations.RemoveField(
            model_name='daycaresubscription',
            name='trial_end_date',
        ),
        migrations.RemoveField(
            model_name='daycaresubscription',
            name='trial_start_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='administrative_notes',
        ),
        migrations.RemoveField(
            model_name='student',
            name='child_notes',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dietary_restrictions',
        ),
        migrations.RemoveField(
            model_name='student',
            name='language',
        ),
        migrations.RemoveField(
            model_name='student',
            name='medical_notes',
        ),
        migrations.RemoveField(
            model_name='student',
            name='preferred_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='special_needs',
        ),
        migrations.RemoveField(
            model_name='studentemergencycontact',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='studentemergencycontact',
            name='pending_changes',
        ),
        migrations.RemoveField(
            model_name='studentpickup',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='studentpickup',
            name='id_proof_status',
        ),
        migrations.RemoveField(
            model_name='studentpickup',
            name='pending_changes',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='features',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_branches',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_classrooms',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_storage_mb',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_students',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='monthly_price',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='quarterly_price',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='status',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='trial_days',
        ),
        migrations.RemoveField(
            model_name='systemannouncement',
            name='target_daycares',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='activities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='compliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='csv_export',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='documents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='fees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='gallery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='pdf_export',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='childenrollment',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.registrationapplication'),
        ),
        migrations.AlterField(
            model_name='childenrollment',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='childenrollment',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='childenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AlterField(
            model_name='childenrollment',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='childvaccinationrecord',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='childvaccinationrecord',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.document'),
        ),
        migrations.AlterField(
            model_name='childvaccinationrecord',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='childvaccinationrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AlterField(
            model_name='childvaccinationrecord',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='consentform',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='consentform',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consentform',
            name='daycare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.daycare'),
        ),
        migrations.AlterField(
            model_name='consentform',
            name='form_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='consentform',
            name='requires_signature',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='consentform',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='consentform',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='consentform',
            name='version',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='consentformassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consentformassignment',
            name='consent_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consentform'),
        ),
        migrations.AlterField(
            model_name='consentformassignment',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='consentformassignment',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.family'),
        ),
        migrations.AlterField(
            model_name='consentformassignment',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='consentformassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AlterField(
            model_name='consentformassignment',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='consentformsignature',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.consentformassignment'),
        ),
        migrations.AlterField(
            model_name='consentformsignature',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='consentformsignature',
            name='ip_address',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.AlterField(
            model_name='consentformsignature',
            name='signed_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='consentformsignature',
            name='signed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='daycareemergencyinformation',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='daycareemergencyinformation',
            name='daycare',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.daycare'),
        ),
        migrations.AlterField(
            model_name='daycareemergencyinformation',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='daycareemergencyinformation',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='daycareholiday',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='daycareholiday',
            name='daycare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.daycare'),
        ),
        migrations.AlterField(
            model_name='daycareholiday',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='daycareholiday',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='daycarelicense',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='daycarelicense',
            name='daycare',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.daycare'),
        ),
        migrations.AlterField(
            model_name='daycarelicense',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='daycarelicense',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='daycaresettings',
            name='allow_parent_notifications',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='daycaresettings',
            name='allow_staff_notifications',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='daycaresettings',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='daycaresettings',
            name='currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='daycaresettings',
            name='date_format',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='daycaresettings',
            name='daycare',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.daycare'),
        ),
        migrations.AlterField(
            model_name='daycaresettings',
            name='default_language',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='daycaresettings',
            name='time_format',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='daycaresettings',
            name='timezone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='daycaresettings',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='daycaresettings',
            name='week_start_day',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='daycare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.daycare'),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='fields_schema',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='is_required',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='version',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='family',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='family',
            name='daycare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.daycare'),
        ),
        migrations.AlterField(
            model_name='family',
            name='primary_email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='family',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='familyauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='familyauditlog',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='familyauditlog',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.family'),
        ),
        migrations.AlterField(
            model_name='familychild',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='familychild',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.family'),
        ),
        migrations.AlterField(
            model_name='familychild',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AlterField(
            model_name='familyguardian',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='familyguardian',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.family'),
        ),
        migrations.AlterField(
            model_name='familyguardian',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.guardian'),
        ),
        migrations.AlterField(
            model_name='familyguardian',
            name='is_primary',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='familyguardian',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='familymessage',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='familymessage',
            name='daycare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.daycare'),
        ),
        migrations.AlterField(
            model_name='familymessage',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.family'),
        ),
        migrations.AlterField(
            model_name='familymessage',
            name='is_read',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='familymessage',
            name='message_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='familymessage',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.familymessage'),
        ),
        migrations.AlterField(
            model_name='familymessage',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='familymessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corefamilymessage_sender_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='familymessage',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='daycare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.daycare'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guardiancommunicationpreference',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='guardiancommunicationpreference',
            name='email_alerts',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='guardiancommunicationpreference',
            name='emergency_alerts_only',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='guardiancommunicationpreference',
            name='guardian',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.guardian'),
        ),
        migrations.AlterField(
            model_name='guardiancommunicationpreference',
            name='sms_alerts',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='guardiancommunicationpreference',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='guardianinvitation',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='guardianinvitation',
            name='daycare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.daycare'),
        ),
        migrations.AlterField(
            model_name='guardianinvitation',
            name='email',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='guardianinvitation',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guardianinvitation',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='guardianinvitation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AlterField(
            model_name='guardianinvitation',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='guardianpasswordresettoken',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='guardianpasswordresettoken',
            name='used',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='guardianpasswordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registrationapplication',
            name='access_token',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='registrationapplication',
            name='applicant_email',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='registrationapplication',
            name='application_data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='registrationapplication',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='registrationapplication',
            name='daycare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.daycare'),
        ),
        migrations.AlterField(
            model_name='registrationapplication',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationapplication',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee'),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subscriptioninvoice',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptioninvoice',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subscriptioninvoice',
            name='daycare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.daycare'),
        ),
        migrations.AlterField(
            model_name='subscriptioninvoice',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriptioninvoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.daycaresubscription'),
        ),
        migrations.AlterField(
            model_name='subscriptioninvoice',
            name='tax',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptioninvoice',
            name='total',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptioninvoice',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='daycare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.daycare'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subscriptioninvoice'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='payment_status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.daycaresubscription'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='daycare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.daycare'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='supportticketmessage',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='supportticketmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supportticket'),
        ),
        migrations.AlterField(
            model_name='systemannouncement',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='systemannouncement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemannouncement',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='systemannouncement',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee'),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='classroomstudent',
            unique_together={('classroom', 'student')},
        ),
        migrations.CreateModel(
            name='ClassroomStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCompensation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pay_type', models.CharField(max_length=50)),
                ('salary_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='CAD', max_length=10)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_history', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='employee_documents/')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='uploaded', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employment_type', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('reason_for_change', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlanFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriptionfeature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subscriptionfeature')),
                ('subscriptionplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='SystemAnnouncementTargetDaycares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.daycare')),
                ('systemannouncement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.systemannouncement')),
            ],
        ),
        migrations.DeleteModel(
            name='WaitlistEntry',
        ),
    ]
