# Generated by Django 6.0.7 on 2026-08-29 14:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_manageddaycare_manageddaycaresubscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child_first_name', models.CharField(max_length=100)),
                ('child_last_name', models.CharField(max_length=100)),
                ('child_dob', models.DateField(blank=True, null=True)),
                ('applicant_name', models.CharField(max_length=200)),
                ('applicant_email', models.CharField(max_length=254)),
                ('applicant_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('requested_start_date', models.DateField(blank=True, null=True)),
                ('preferred_program', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.IntegerField()),
                ('waitlist_date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.registrationapplication')),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.daycare')),
            ],
        ),
    ]
