# Generated by Django 6.0.7 on 2026-08-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_waitlistentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenthistory',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='employment_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='job_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
