# Generated by Django 6.0.7 on 2026-08-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_employmenthistory_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
