# Generated by Django 6.0.7 on 2026-08-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_student_preferred_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='administrative_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='child_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='dietary_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='special_needs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
