# Generated by Django 6.0.7 on 2026-08-30 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_student_administrative_notes_student_child_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='core.agegroup'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='core.branch'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
