# Generated by Django 6.0.7 on 2026-09-01 16:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_provinces_and_credential_types(apps, schema_editor):
    Province = apps.get_model('core', 'Province')
    CredentialType = apps.get_model('core', 'CredentialType')

    provinces_data = [
        {'code': 'ON', 'name': 'Ontario', 'status': 'Active'},
        {'code': 'BC', 'name': 'British Columbia', 'status': 'Active'},
        {'code': 'AB', 'name': 'Alberta', 'status': 'Active'},
        {'code': 'QC', 'name': 'Quebec', 'status': 'Active'},
        {'code': 'MB', 'name': 'Manitoba', 'status': 'Active'},
        {'code': 'SK', 'name': 'Saskatchewan', 'status': 'Active'},
        {'code': 'NS', 'name': 'Nova Scotia', 'status': 'Active'},
        {'code': 'NB', 'name': 'New Brunswick', 'status': 'Active'},
        {'code': 'NL', 'name': 'Newfoundland and Labrador', 'status': 'Active'},
        {'code': 'PE', 'name': 'Prince Edward Island', 'status': 'Active'},
        {'code': 'NT', 'name': 'Northwest Territories', 'status': 'Active'},
        {'code': 'YT', 'name': 'Yukon', 'status': 'Active'},
        {'code': 'NU', 'name': 'Nunavut', 'status': 'Active'},
    ]

    for p in provinces_data:
        Province.objects.get_or_create(code=p['code'], defaults={'name': p['name'], 'status': p['status']})

    credential_types_data = [
        {
            'name': 'ECE Qualification',
            'description': 'Early Childhood Educator Professional Qualification',
            'requires_expiry': True,
            'requires_certificate_number': True
        },
        {
            'name': 'ECE Certificate',
            'description': 'Provincial Early Childhood Education Certificate',
            'requires_expiry': True,
            'requires_certificate_number': True
        },
        {
            'name': 'ECE Diploma',
            'description': 'Two-year College Diploma in Early Childhood Education',
            'requires_expiry': False,
            'requires_certificate_number': True
        },
        {
            'name': 'ECE Degree',
            'description': 'Bachelor of Early Childhood Leadership / Studies Degree',
            'requires_expiry': False,
            'requires_certificate_number': True
        },
        {
            'name': 'Other approved credential',
            'description': 'Other Ministry/College approved early childhood education credential',
            'requires_expiry': True,
            'requires_certificate_number': False
        },
    ]

    for ct in credential_types_data:
        CredentialType.objects.get_or_create(name=ct['name'], defaults={
            'description': ct['description'],
            'requires_expiry': ct['requires_expiry'],
            'requires_certificate_number': ct['requires_certificate_number'],
            'status': 'Active'
        })


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_remove_subscriptionplan_activities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CredentialType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('requires_expiry', models.BooleanField(default=True)),
                ('requires_certificate_number', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credential_types', to='core.province')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ECECredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Pending Renewal', 'Pending Renewal'), ('Suspended', 'Suspended'), ('Revoked', 'Revoked'), ('Inactive', 'Inactive')], default='Active', max_length=50)),
                ('verification_status', models.CharField(choices=[('Unverified', 'Unverified'), ('Pending Verification', 'Pending Verification'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Unverified', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='core.credentialtype')),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ece_credentials', to='core.daycare')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ece_credentials', to='core.employee')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='core.province')),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.RunPython(seed_provinces_and_credential_types, reverse_code=migrations.RunPython.noop),
    ]
