# Generated by Django 6.0.7 on 2026-09-02 03:11

import django.db.models.deletion
from django.db import migrations, models


def seed_phase2_credential_types(apps, schema_editor):
    CredentialType = apps.get_model('core', 'CredentialType')

    types_data = [
        # ECE
        {
            'name': 'ECE Qualification',
            'category': 'ece',
            'description': 'Early Childhood Educator Professional Qualification',
            'requires_expiry': True,
            'requires_certificate_number': True,
            'default_validity_months': 36
        },
        {
            'name': 'ECE Certificate',
            'category': 'ece',
            'description': 'Provincial Early Childhood Education Certificate',
            'requires_expiry': True,
            'requires_certificate_number': True,
            'default_validity_months': 36
        },
        {
            'name': 'ECE Diploma',
            'category': 'ece',
            'description': 'Two-year College Diploma in Early Childhood Education',
            'requires_expiry': False,
            'requires_certificate_number': True,
            'default_validity_months': None
        },
        {
            'name': 'ECE Degree',
            'category': 'ece',
            'description': 'Bachelor of Early Childhood Leadership / Studies Degree',
            'requires_expiry': False,
            'requires_certificate_number': True,
            'default_validity_months': None
        },
        {
            'name': 'Other approved ECE credential',
            'category': 'ece',
            'description': 'Other Ministry/College approved early childhood education credential',
            'requires_expiry': True,
            'requires_certificate_number': False,
            'default_validity_months': 36
        },

        # Certifications
        {
            'name': 'Standard First Aid & CPR Level C',
            'category': 'certification',
            'description': 'Standard First Aid and CPR-C certification for childcare educators',
            'requires_expiry': True,
            'requires_certificate_number': True,
            'default_validity_months': 36
        },
        {
            'name': 'Emergency First Aid & CPR Level B/C',
            'category': 'certification',
            'description': 'Emergency First Aid and CPR certification',
            'requires_expiry': True,
            'requires_certificate_number': True,
            'default_validity_months': 36
        },
        {
            'name': 'CPR / AED Level C (Annual Renewal)',
            'category': 'certification',
            'description': 'Cardiopulmonary Resuscitation Level C with AED annual certification',
            'requires_expiry': True,
            'requires_certificate_number': True,
            'default_validity_months': 12
        },
        {
            'name': 'Food Handler / Food Safety Certification',
            'category': 'certification',
            'description': 'Provincial Certified Food Handler certification for kitchen & classroom food prep',
            'requires_expiry': True,
            'requires_certificate_number': True,
            'default_validity_months': 60
        },

        # Background Checks
        {
            'name': 'Vulnerable Sector Check (VSC)',
            'category': 'background_check',
            'description': 'Police Vulnerable Sector Check for working with children',
            'requires_expiry': True,
            'requires_certificate_number': False,
            'default_validity_months': 60
        },
        {
            'name': 'Criminal Record and Judicial Matters Check (CRJMC)',
            'category': 'background_check',
            'description': 'Criminal background and judicial matters police check',
            'requires_expiry': True,
            'requires_certificate_number': False,
            'default_validity_months': 60
        },
        {
            'name': 'Annual Offence Declaration',
            'category': 'background_check',
            'description': 'Annual signed offence declaration for returning employees',
            'requires_expiry': True,
            'requires_certificate_number': False,
            'default_validity_months': 12
        },

        # Training
        {
            'name': 'Child Protection & Duty to Report Training',
            'category': 'training',
            'description': 'Training on child abuse recognition, reporting procedures, and child protection acts',
            'requires_expiry': True,
            'requires_certificate_number': False,
            'default_validity_months': 12
        },
        {
            'name': 'WHMIS Workplace Hazardous Materials',
            'category': 'training',
            'description': 'Workplace Hazardous Materials Information System training',
            'requires_expiry': True,
            'requires_certificate_number': False,
            'default_validity_months': 12
        },
        {
            'name': 'Anaphylaxis & Emergency Medical Response',
            'category': 'training',
            'description': 'Individualized anaphylaxis plan and epinephrine auto-injector training',
            'requires_expiry': True,
            'requires_certificate_number': False,
            'default_validity_months': 12
        },
        {
            'name': 'Fire Safety & Emergency Evacuation',
            'category': 'training',
            'description': 'Daycare emergency preparedness, fire drill, and evacuation training',
            'requires_expiry': True,
            'requires_certificate_number': False,
            'default_validity_months': 12
        },
        {
            'name': 'Occupational Health & Safety Awareness',
            'category': 'training',
            'description': 'Health and safety awareness in 4 steps for workers',
            'requires_expiry': False,
            'requires_certificate_number': False,
            'default_validity_months': None
        },
    ]

    for item in types_data:
        CredentialType.objects.update_or_create(
            name=item['name'],
            defaults={
                'category': item['category'],
                'description': item['description'],
                'requires_expiry': item['requires_expiry'],
                'requires_certificate_number': item['requires_certificate_number'],
                'default_validity_months': item['default_validity_months'],
                'status': 'Active'
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_credentialtype_province_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credentialtype',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='credentialtype',
            name='category',
            field=models.CharField(choices=[('ece', 'ECE Credential'), ('certification', 'Certification'), ('background_check', 'Background Check'), ('training', 'Required Training'), ('other', 'Other')], default='ece', max_length=50),
        ),
        migrations.AddField(
            model_name='credentialtype',
            name='default_validity_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ececredential',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ececredential',
            name='document_reference',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='ececredential',
            name='issuing_organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ececredential',
            name='request_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ececredential',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to='core.province'),
        ),
        migrations.AlterField(
            model_name='ececredential',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Pending Renewal', 'Pending Renewal'), ('Suspended', 'Suspended'), ('Revoked', 'Revoked'), ('Inactive', 'Inactive'), ('Pending Review', 'Pending Review'), ('Requires Review', 'Requires Review')], default='Active', max_length=50),
        ),
        migrations.RunPython(seed_phase2_credential_types, reverse_code=migrations.RunPython.noop),
    ]
