# Generated by Django 6.0.7 on 2026-09-02 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_credentialtype_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ececredential',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='credential_documents/'),
        ),
        migrations.AddField(
            model_name='ececredential',
            name='document_status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('pending_review', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='uploaded', max_length=50),
        ),
        migrations.AddField(
            model_name='ececredential',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ececredential',
            name='previous_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_credentials', to='core.ececredential'),
        ),
        migrations.AddField(
            model_name='ececredential',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ececredential',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ececredential',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ececredential',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Pending Renewal', 'Pending Renewal'), ('Suspended', 'Suspended'), ('Revoked', 'Revoked'), ('Inactive', 'Inactive'), ('Pending Review', 'Pending Review'), ('Requires Review', 'Requires Review'), ('Superseded', 'Superseded')], default='Active', max_length=50),
        ),
    ]
