# Generated by Django 6.0.7 on 2026-09-02 10:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_remove_employeedocument_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeavailability',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable'), ('Custom hours', 'Custom hours')], default='Available', max_length=50),
        ),
        migrations.CreateModel(
            name='StaffSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('shift_type', models.CharField(choices=[('regular', 'Regular'), ('opening', 'Opening'), ('closing', 'Closing'), ('custom', 'Custom')], default='regular', max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_schedules', to='core.branch')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_schedules', to='core.classroom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_schedules', to='core.daycare')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.employee')),
            ],
            options={
                'ordering': ['date', 'shift_start'],
                'indexes': [models.Index(fields=['daycare', 'date'], name='core_staffs_daycare_f845c8_idx'), models.Index(fields=['employee', 'date'], name='core_staffs_employe_01d65d_idx')],
            },
        ),
    ]

