# Generated by Django 6.0.7 on 2026-09-02 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_remove_employeedocument_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffschedule',
            name='duties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ShiftBreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('break_start', models.TimeField()),
                ('break_end', models.TimeField()),
                ('break_type', models.CharField(choices=[('meal', 'Meal Break'), ('rest', 'Rest Break'), ('other', 'Other Break')], default='meal', max_length=50)),
                ('is_paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='core.staffschedule')),
            ],
            options={
                'ordering': ['break_start'],
                'indexes': [models.Index(fields=['schedule', 'break_start'], name='core_shiftb_schedul_c5c186_idx')],
            },
        ),
    ]

