# Generated by Django 6.0.7 on 2026-09-02 12:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_remove_employeedocument_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRecord',

            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('scheduled_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('regular_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overtimes', to=settings.AUTH_USER_MODEL)),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_records', to='core.daycare')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_records', to='core.employee')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_shift_swaps', to=settings.AUTH_USER_MODEL)),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_swap_requests', to='core.daycare')),
                ('requesting_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_sent', to='core.employee')),
                ('requesting_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_as_source', to='core.staffschedule')),
                ('target_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_received', to='core.employee')),
                ('target_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_requests_as_target', to='core.staffschedule')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeBankRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('max_balance_hours', models.DecimalField(decimal_places=2, default=40.0, max_digits=6)),
                ('require_approval', models.BooleanField(default=True)),
                ('expiry_months', models.IntegerField(blank=True, default=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daycare', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_bank_rules', to='core.daycare')),
            ],
        ),
        migrations.CreateModel(
            name='TimeBankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('overtime_credit', 'Overtime Credit'), ('time_off_debit', 'Time-off Debit'), ('manual_adjustment', 'Manual Adjustment'), ('correction', 'Correction')], max_length=50)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('reason', models.TextField()),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timebank_txns', to=settings.AUTH_USER_MODEL)),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_bank_transactions', to='core.daycare')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_bank_transactions', to='core.employee')),
                ('overtime_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_bank_credits', to='core.overtimerecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='overtimerecord',
            index=models.Index(fields=['daycare', 'date'], name='core_overti_daycare_756db8_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimerecord',
            index=models.Index(fields=['employee', 'date'], name='core_overti_employe_5ab290_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimerecord',
            index=models.Index(fields=['status'], name='core_overti_status_a8508f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='overtimerecord',
            unique_together={('employee', 'date')},
        ),
        migrations.AddIndex(
            model_name='shiftswaprequest',
            index=models.Index(fields=['daycare', 'status'], name='core_shifts_daycare_f9dcd7_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftswaprequest',
            index=models.Index(fields=['requesting_employee', 'status'], name='core_shifts_request_c1ab06_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftswaprequest',
            index=models.Index(fields=['target_employee', 'status'], name='core_shifts_target__c73a02_idx'),
        ),
        migrations.AddIndex(
            model_name='timebanktransaction',
            index=models.Index(fields=['daycare', 'employee'], name='core_timeba_daycare_78a361_idx'),
        ),
        migrations.AddIndex(
            model_name='timebanktransaction',
            index=models.Index(fields=['employee', 'date'], name='core_timeba_employe_3f0dc8_idx'),
        ),
    ]
