# Generated by Django 6.0.7 on 2026-09-02 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_remove_employeedocument_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',

            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('is_paid', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('color_code', models.CharField(default='#4F46E5', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='core.daycare')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('daycare', 'code')},
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('affected_shifts_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='core.daycare')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='core.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.leavetype')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['daycare', 'status'], name='core_leaver_daycare_26515d_idx'), models.Index(fields=['employee', 'start_date'], name='core_leaver_employe_70c496_idx'), models.Index(fields=['start_date', 'end_date'], name='core_leaver_start_d_c8e553_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('leave_requested', 'Leave Requested'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('shift_affected', 'Shift Coverage Affected'), ('staff_shortage', 'Staff Shortage Alert')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_notifications', to='core.daycare')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.employee')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['daycare', 'user', 'is_read'], name='core_staffn_daycare_34d0f4_idx'), models.Index(fields=['created_at'], name='core_staffn_created_bef5c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffShortageAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('alert_level', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], default='critical', max_length=20)),
                ('required_staff', models.IntegerField(default=1)),
                ('scheduled_staff', models.IntegerField(default=0)),
                ('shortage_count', models.IntegerField(default=0)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active Shortage'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortage_alerts', to='core.classroom')),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortage_alerts', to='core.daycare')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['daycare', 'date'], name='core_staffs_daycare_ab5b6b_idx'), models.Index(fields=['status'], name='core_staffs_status_f19407_idx'), models.Index(fields=['alert_level'], name='core_staffs_alert_l_534ff7_idx')],
            },
        ),
    ]
