# Generated by Django 6.0.7 on 2026-09-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_remove_employeedocument_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentattendance',
            options={'ordering': ['-attendance_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='arrival_type',
            field=models.CharField(blank=True, default='STANDARD', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='core.branch'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='departure_type',
            field=models.CharField(blank=True, default='STANDARD', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='early_pickup_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='core.childenrollment'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='expected_arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='expected_departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='is_early_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='late_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='attendance_status',
            field=models.CharField(default='PRESENT', max_length=50),
        ),
    ]
