# Generated by Django 6.0.7 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_remove_employeedocument_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
