# Generated by Django 6.0.7 on 2026-09-02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_remove_employeedocument_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffBreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('break_start', models.DateTimeField()),
                ('break_end', models.DateTimeField(blank=True, null=True)),
                ('break_type', models.CharField(choices=[('MEAL', 'Meal Break'), ('REST', 'Rest Break'), ('OTHER', 'Other Break')], default='MEAL', max_length=50)),
                ('is_paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['break_start'],
            },
        ),
        migrations.AlterModelOptions(
            name='staffattendance',
            options={'ordering': ['-date', '-clock_in']},
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CORRECTED', 'Corrected')], default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_staff_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_attendances', to='core.branch'),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_attendances', to='core.classroom'),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='clock_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='clock_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='corrected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='corrected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_staff_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='correction_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='daycare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendances', to='core.daycare'),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='is_corrected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='scheduled_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='core.staffschedule'),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_staff_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendances', to='core.employee'),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_staff_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='status',
            field=models.CharField(default='CLOCKED_IN', max_length=50),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['daycare', 'date'], name='core_staffa_daycare_857530_idx'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['employee', 'date'], name='core_staffa_employe_21b8a5_idx'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['status'], name='core_staffa_status_841dd8_idx'),
        ),
        migrations.AddField(
            model_name='staffbreak',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='core.staffattendance'),
        ),
        migrations.AddIndex(
            model_name='staffbreak',
            index=models.Index(fields=['attendance', 'break_start'], name='core_staffb_attenda_d4d0f7_idx'),
        ),
    ]
