# Generated by Django on 2026-09-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_staffbreak_alter_staffattendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendance',
            name='approval_status',
            field=models.CharField(
                choices=[
                    ('DRAFT', 'Draft'),
                    ('SUBMITTED', 'Submitted for Approval'),
                    ('APPROVED', 'Approved'),
                    ('REJECTED', 'Rejected'),
                    ('CORRECTION_REQUIRED', 'Correction Required'),
                    ('PENDING', 'Pending Approval'),
                    ('CORRECTED', 'Corrected')
                ],
                default='PENDING',
                max_length=50
            ),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='submitted_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='submitted_staff_attendances',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='attendance',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='overtime_records',
                to='core.staffattendance'
            ),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='source',
            field=models.CharField(default='attendance', max_length=100),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
