# Generated by Django 6.0.7 on 2026-09-04 03:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_authorized_pickup_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatioRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('min_age_months', models.IntegerField(default=0)),
                ('max_age_months', models.IntegerField(default=72)),
                ('max_children_per_staff', models.IntegerField(default=5)),
                ('warning_threshold_buffer', models.IntegerField(default=1)),
                ('requires_qualified_ece', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratio_rules', to='core.agegroup')),
                ('daycare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratio_rules', to='core.daycare')),
            ],
            options={
                'ordering': ['min_age_months', 'name'],
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='ratio_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='core.ratiorule'),
        ),
    ]
