# Generated by Django 6.0.7 on 2026-09-05 11:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_remove_employeedocument_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupQRToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_qr_tokens', to='core.daycare')),
                ('pickup_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='core.studentpickup')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_qr_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickupSecurityPIN',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pin_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('failed_attempts_count', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_pins', to='core.daycare')),
                ('pickup_person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_pin', to='core.studentpickup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafeArrivalDepartureEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out'), ('VERIFICATION_FAILED', 'Verification Failed')], max_length=50)),
                ('verification_method', models.CharField(choices=[('MANUAL', 'Manual'), ('QR', 'QR Code'), ('PIN', 'PIN'), ('DIGITAL_SIGNATURE', 'Digital Signature')], default='MANUAL', max_length=50)),
                ('verification_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=50)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('signature_data', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('device_metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_departure_events', to='core.studentattendance')),
                ('authorized_pickup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_departure_events', to='core.studentpickup')),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_departure_events', to='core.daycare')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_arrival_departure_events', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_departure_events', to='core.student')),
            ],
            options={
                'ordering': ['-timestamp', '-created_at'],
            },
        ),
    ]
