# Generated by Django 6.0.7 on 2026-09-05 13:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_remove_employeedocument_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safearrivaldepartureevent',
            name='actual_checkout_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safearrivaldepartureevent',
            name='attempted_person_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='safearrivaldepartureevent',
            name='expected_pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safearrivaldepartureevent',
            name='is_late_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='safearrivaldepartureevent',
            name='late_duration_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='safearrivaldepartureevent',
            name='event_type',
            field=models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out'), ('LATE_PICKUP', 'Late Pickup'), ('UNAUTHORIZED_ATTEMPT', 'Unauthorized Attempt'), ('VERIFICATION_FAILED', 'Verification Failed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='staffnotification',
            name='notification_type',
            field=models.CharField(choices=[('leave_requested', 'Leave Requested'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('shift_affected', 'Shift Coverage Affected'), ('staff_shortage', 'Staff Shortage Alert'), ('child_not_arrived', 'Child Not Checked In'), ('child_missing_checkout', 'Missing Child Checkout'), ('attendance_correction', 'Attendance Correction'), ('timesheet_submitted', 'Timesheet Submitted'), ('timesheet_approved', 'Timesheet Approved'), ('timesheet_rejected', 'Timesheet Rejected'), ('missing_staff_clockout', 'Missing Staff Clock-Out'), ('overtime_approval_required', 'Overtime Approval Required'), ('unauthorized_pickup_attempt', 'Unauthorized Pickup Attempt'), ('late_pickup_recorded', 'Late Pickup Recorded')], max_length=50),
        ),
    ]
