# Generated by Django 6.0.7 on 2026-09-12 08:51

import datetime
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_billing_phase4_payments_subsidies_tax'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='childsubsidyprofile',
            new_name='core_childs_daycare_6a82dd_idx',
            old_name='core_childs_daycare_5f12ab_idx',
        ),
        migrations.RenameIndex(
            model_name='childsubsidyprofile',
            new_name='core_childs_effecti_88eb19_idx',
            old_name='core_childs_effecti_7890cd_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='core_paymen_daycare_68eb8b_idx',
            old_name='core_paymen_daycare_ef45ab_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='core_paymen_invoice_cf3653_idx',
            old_name='core_paymen_invoice_9a8712_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='core_paymen_receipt_f19e07_idx',
            old_name='core_paymen_receipt_1234ab_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='core_paymen_family__9d890a_idx',
            old_name='core_paymen_family__3456cd_idx',
        ),
        migrations.RenameIndex(
            model_name='taxreceipt',
            new_name='core_taxrec_daycare_5a2d6c_idx',
            old_name='core_taxrec_daycare_3456ef_idx',
        ),
        migrations.RenameIndex(
            model_name='taxreceipt',
            new_name='core_taxrec_family__4bcb40_idx',
            old_name='core_taxrec_family__7890ab_idx',
        ),
        migrations.RenameIndex(
            model_name='taxreceipt',
            new_name='core_taxrec_receipt_71d105_idx',
            old_name='core_taxrec_receipt_cdef12_idx',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='compliance',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='csv_export',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='notifications',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='pdf_export',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='price',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='reports',
        ),
        migrations.AddField(
            model_name='daycaresubscription',
            name='trial_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daycaresubscription',
            name='trial_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='childvaccinationrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='childvaccinationrecord',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='childvaccinationrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='daycareemergencyinformation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='daycareemergencyinformation',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='daycareholiday',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='daycareholiday',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='daycareholiday',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='daycarelicense',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='daycarelicense',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='daycarelicense',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='effective_from',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='family',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='familyauditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='familychild',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='familychild',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_children', to='core.family'),
        ),
        migrations.AlterField(
            model_name='familychild',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_families', to='core.student'),
        ),
        migrations.AlterField(
            model_name='familyguardian',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='familyguardian',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_guardians', to='core.family'),
        ),
        migrations.AlterField(
            model_name='familyguardian',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_families', to='core.guardian'),
        ),
        migrations.AlterField(
            model_name='familyguardian',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='familyguardian',
            name='relationship',
            field=models.CharField(default='Guardian', max_length=100),
        ),
        migrations.AlterField(
            model_name='familyguardian',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardian_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guardiancommunicationpreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='guardiancommunicationpreference',
            name='email_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='guardiancommunicationpreference',
            name='emergency_alerts_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guardiancommunicationpreference',
            name='guardian',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_preference', to='core.guardian'),
        ),
        migrations.AlterField(
            model_name='guardiancommunicationpreference',
            name='sms_alerts',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guardiancommunicationpreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='guardianinvitation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='guardianinvitation',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='guardianpasswordresettoken',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='guardianpasswordresettoken',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='latefeerule',
            name='effective_from',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='registrationapplication',
            name='access_token',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='registrationapplication',
            name='application_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='registrationapplication',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='registrationapplication',
            name='status',
            field=models.CharField(default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationapplication',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='siblingdiscountrule',
            name='effective_from',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='staffnotification',
            name='notification_type',
            field=models.CharField(choices=[('leave_requested', 'Leave Requested'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('shift_affected', 'Shift Coverage Affected'), ('staff_shortage', 'Staff Shortage Alert'), ('child_not_arrived', 'Child Not Checked In'), ('child_missing_checkout', 'Missing Child Checkout'), ('attendance_correction', 'Attendance Correction'), ('timesheet_submitted', 'Timesheet Submitted'), ('timesheet_approved', 'Timesheet Approved'), ('timesheet_rejected', 'Timesheet Rejected'), ('missing_staff_clockout', 'Missing Staff Clock-Out'), ('overtime_approval_required', 'Overtime Approval Required'), ('unauthorized_pickup_attempt', 'Unauthorized Pickup Attempt'), ('late_pickup_recorded', 'Late Pickup Recorded'), ('daily_report_published', 'Daily Report Published')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='core.classroomstudent'),
        ),
        migrations.AlterField(
            model_name='studentpickup',
            name='authorization_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('PENDING_VERIFICATION', 'Pending Verification'), ('PENDING_APPROVAL', 'Pending Approval'), ('REJECTED', 'Rejected')], default='ACTIVE', max_length=50),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['daycare', 'family', 'status'], name='core_credit_daycare_41e8dd_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['transaction_type'], name='core_credit_transac_72bf04_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['created_at'], name='core_credit_created_5b5c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='discountrule',
            index=models.Index(fields=['daycare', 'is_active'], name='core_discou_daycare_a768b0_idx'),
        ),
        migrations.AddIndex(
            model_name='discountrule',
            index=models.Index(fields=['applies_to', 'is_active'], name='core_discou_applies_35f193_idx'),
        ),
        migrations.AddIndex(
            model_name='discountrule',
            index=models.Index(fields=['effective_from', 'effective_until'], name='core_discou_effecti_83281e_idx'),
        ),
        migrations.AddIndex(
            model_name='latefeerule',
            index=models.Index(fields=['daycare', 'is_active'], name='core_latefe_daycare_1d1b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='latefeerule',
            index=models.Index(fields=['effective_from', 'effective_until'], name='core_latefe_effecti_b7e1ad_idx'),
        ),
        migrations.AddIndex(
            model_name='siblingdiscountrule',
            index=models.Index(fields=['daycare', 'is_active'], name='core_siblin_daycare_3b9d21_idx'),
        ),
        migrations.AddIndex(
            model_name='siblingdiscountrule',
            index=models.Index(fields=['effective_from', 'effective_until'], name='core_siblin_effecti_7f0243_idx'),
        ),
    ]
